### ISSUE TITLE
Bug Report: Account Entries

### ISSUE THREAD

**Issue by Ribeccalin** [mifosio/fims-web-app#10]
No account entry information exists for entries made in the Tea Consumption Ledger.

I added two expenses, one for teaspoons and one for Oolong tea to the Tea Consumption ledger.  The amounts (201, and 30 respectively) were added to the Trial Balance Ledger, but I can not find entries under the Tea Consumption ledger.

I started on main accounting page, clicking on Tea Consumption (which shows an expense):
![screenshot 88](https://cloud.githubusercontent.com/assets/28103295/25490759/65b92272-2b33-11e7-81c6-2a259169a9dd.png)
There is no sub-ledger information listed.  Clicked on Accounts:
![screenshot 89](https://cloud.githubusercontent.com/assets/28103295/25490763/6abea314-2b33-11e7-92f6-0eec5becdd7a.png)
Accounts for ledger shows an expense.  Clicked on Show:
![screenshot 91](https://cloud.githubusercontent.com/assets/28103295/25490767/6ff3465a-2b33-11e7-8158-fc75d4f92964.png)
Clicked on Account entries:
![screenshot 92](https://cloud.githubusercontent.com/assets/28103295/25490773/769ffc50-2b33-11e7-9710-6e361a20ac7b.png)
There are no entries listed for this account:
![screenshot 93](https://cloud.githubusercontent.com/assets/28103295/25490778/7a97dfc6-2b33-11e7-9280-d0432697a483.png)

**Comment by crain** [comment]
Currently I can't reproduce this issue.

> I added two expenses, one for teaspoons and one for Oolong tea to the Tea Consumption ledger. The amounts (201, and 30 respectively) were added to the Trial Balance Ledger, but I can not find entries under the Tea Consumption ledger.

If you want to do a manual transaction you have to create a new journal entry(under General Ledger -> Journal Entries) and choose the accounts you want to credit and debit.

Just to double check: As the balance for account "Tea" shows a balance of 201 did you created that account with an initial balance? 
If yes, there will be no account entry as the initial balance is set right on the account itself without generating an account entry.
