### ISSUE TITLE
Bug Report: Country abbreviation and name

### ISSUE THREAD

**Issue by Ribeccalin** [mifosio/fims-web-app#12]
When inputting client information, the country abbreviation and the country name do not have to correlate and there is no verification if the abbreviation or country are correct.
![screenshot 100](https://cloud.githubusercontent.com/assets/28103295/25524639/15298790-2bd1-11e7-8a39-ec33838da895.png)

**Comment by crain** [comment]
Country code was removed from customer and office address form. The user only has to select a country out of the autocomplete and the country code is set in the background not visible to the user.
