### ISSUE TITLE
Bug Report: Email verification 

### ISSUE THREAD

**Issue by Ribeccalin** [mifosio/fims-web-app#13]
When creating a customer, email addresses inputted are not required to have an @ symbol.
![screenshot 101](https://cloud.githubusercontent.com/assets/28103295/25524796/a0349c62-2bd1-11e7-9281-efea9438fa28.png)

**Comment by crain** [comment]
I am waiting for a fix that allows to use an email validator on optional fields.

**Comment by Ribeccalin** [comment]
Transferred to JIRA

**Comment by crain** [comment]
Fixed with #50
