### ISSUE TITLE
Bug Report: No Error message for duplicate employee ID

### ISSUE THREAD

**Issue by Ribeccalin** [mifosio/fims-web-app#16]
There is an employee with the user name "Alex".  I wanted to see I could create an "alex".  It allows me to input all the information:

![screenshot 108](https://cloud.githubusercontent.com/assets/28103295/25654561/29408cb2-2fb7-11e7-9ba1-f0209ef88703.png)
![screenshot 110](https://cloud.githubusercontent.com/assets/28103295/25654565/2cd9a156-2fb7-11e7-9dea-62942541c53f.png)

The "Create Employee" button is green, but nothing happens when I click it.  I don't get an error message, I just can't move forward.

**Comment by crain** [comment]
@Ribeccalin - I can't reproduce this issue on the latest version. Can you please verify?

**Comment by Ribeccalin** [comment]
I don't seem to have that same problem.  It would be more convenient if the error message showed up when you first click on the "Continue" button below adding the name.

**Comment by crain** [comment]
I will create a seperate enhancement issue.
