### ISSUE TITLE
Select All feature on "Roles"

### ISSUE THREAD

**Issue by Ribeccalin** [mifosio/fims-web-app#18]
Having a "select all" feature for role permission selection (Read, Change, Delete) would be beneficial:
![screenshot 112](https://cloud.githubusercontent.com/assets/28103295/25655973/99efc4a0-2fbc-11e7-8273-8754f53f2b2b.png)

**Comment by crain** [comment]
With #7 I added 3 new checkboxes in the header of the permission list:

![role_multi_select](https://cloud.githubusercontent.com/assets/998744/25709058/844555fc-30e8-11e7-8d30-6f5268e44c31.PNG)

Also, if you select delete permission it will auto fill change and delete for you. Same if you select change it will select read for you.
