### ISSUE TITLE
Office will not delete

### ISSUE THREAD

**Issue by Ribeccalin** [mifosio/fims-web-app#35]
Tried to delete Office AI.  Office won't delete
![screenshot 147](https://cloud.githubusercontent.com/assets/28103295/26595171/1da3c214-4530-11e7-8014-bf99afe91ee7.png)
![screenshot 148](https://cloud.githubusercontent.com/assets/28103295/26595173/1f533f4a-4530-11e7-8211-e79b7e10e024.png)
![screenshot 149](https://cloud.githubusercontent.com/assets/28103295/26595174/2144a118-4530-11e7-9723-487a8fd352b6.png)
![screenshot 150](https://cloud.githubusercontent.com/assets/28103295/26595180/23dc1802-4530-11e7-83b7-aa250b443dfc.png)

**Comment by Ribeccalin** [comment]
I have been able to delete other offices, but not the one with the ID "AI" for some reason

**Comment by crain** [comment]
Yes you are correct, it should appear an error message when the office has branches or employees.
