### ISSUE TITLE
Can not delete office with branch offices

### ISSUE THREAD

**Issue by Ribeccalin** [mifosio/fims-web-app#37]
I Created an office with a branch office under it. 
![screenshot 152](https://cloud.githubusercontent.com/assets/28103295/26596172/72285c3e-4533-11e7-951d-f99572ba3a03.png)

I then tried to delete the parent office and it wouldn't let me, but gave me no error message stating why it couldn't be deleted.

![screenshot 153](https://cloud.githubusercontent.com/assets/28103295/26596196/86defb10-4533-11e7-80a4-b70a5ea585c1.png)

![screenshot 154](https://cloud.githubusercontent.com/assets/28103295/26596247/b0252d32-4533-11e7-82ea-ba3b84863a3c.png)

**Comment by crain** [comment]
![delete_confirmation](https://cloud.githubusercontent.com/assets/998744/26623048/b438dd88-45ec-11e7-94fd-3052bac517b4.PNG)

There will be a alert showing a message why you could not delete the office.
