### ISSUE TITLE
Bug Report: Office Zip Code

### ISSUE THREAD

**Issue by Ribeccalin** [mifosio/fims-web-app#8]
#### Bug Report
![screenshot 84](https://cloud.githubusercontent.com/assets/28103295/25487242/3c39cb36-2b29-11e7-97e6-5ab2f260ad2b.png)

When creating a new office location, I am unable to input an international postal/zip code.  It only accepts 5 digit zip codes.  This would also not allow for zip+4 which is used to speed mail delivery in the US.

**Comment by crain** [comment]
You should now be able to enter zip codes with a length of 32.

**Comment by Ribeccalin** [comment]
I tested this and it seems to be working now.  I did a quick search and it seems the longest postal codes worldwide seem to be about 10 characters, so it could be limited to 10 characters, if desired.
